# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-slim

WORKDIR /app

# Copy the project files
COPY . /app

# Upgrade pip and install the package
RUN pip install --upgrade pip \
    && pip install mcpo uv

# Expose port if needed (optional)
EXPOSE 8004

# Set environment variables
ENV FRESHSERVICE_API_KEY="x"
ENV FRESHSERVICE_DOMAIN="x"

# Set default command
CMD ["uvx", "mcpo", "--host", "0.0.0.0", "--port", "8004", "--", "uvx", "freshservice-mcp"]
